// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyHive.Api.Data;

#nullable disable

namespace StudyHive.Api.Data.Migrations
{
    [DbContext(typeof(StudyHiveDbContext))]
    [Migration("20260820060329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyHive.Api.Data.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecidedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decided_by_role");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_decisions");

                    b.HasIndex("DecidedBy")
                        .HasDatabaseName("ix_approval_decisions_decided_by");

                    b.HasIndex("QuotationId", "DecidedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ad_quote");

                    b.ToTable("approval_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_approval_decisions_decision", "decision IN ('Approved','Rejected','RevisionRequested')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_user");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("budget");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupSize")
                        .HasColumnType("integer")
                        .HasColumnName("group_size");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<DateOnly>("PreferredDateFrom")
                        .HasColumnType("date")
                        .HasColumnName("preferred_date_from");

                    b.Property<DateOnly>("PreferredDateTo")
                        .HasColumnType("date")
                        .HasColumnName("preferred_date_to");

                    b.Property<TimeOnly>("PreferredTimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_time_from");

                    b.Property<TimeOnly>("PreferredTimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_time_to");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_minutes");

                    b.Property<int>("SessionsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sessions_required");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_booking_requests");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_br_status");

                    b.HasIndex("StudentId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_br_student");

                    b.ToTable("booking_requests", null, t =>
                        {
                            t.HasCheckConstraint("chk_date_order", "preferred_date_to >= preferred_date_from");

                            t.HasCheckConstraint("chk_time_order", "preferred_time_to > preferred_time_from");

                            t.HasCheckConstraint("ck_booking_requests_budget", "budget > 0");

                            t.HasCheckConstraint("ck_booking_requests_duration", "session_duration_minutes BETWEEN 30 AND 480");

                            t.HasCheckConstraint("ck_booking_requests_group_size", "group_size BETWEEN 1 AND 50");

                            t.HasCheckConstraint("ck_booking_requests_sessions", "sessions_required BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_booking_requests_status", "status IN ('Draft','Submitted','Processing','PendingApproval','Approved','Rejected','RevisionRequested','Completed','Cancelled','Failed')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequestEquipment", b =>
                {
                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<Guid>("EquipmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_type_id");

                    b.Property<int>("QuantityRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity_required");

                    b.HasKey("BookingRequestId", "EquipmentTypeId")
                        .HasName("pk_booking_request_equipment");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("ix_booking_request_equipment_equipment_type_id");

                    b.ToTable("booking_request_equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_request_equipment_quantity", "quantity_required > 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumable_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_booking_request_items");

                    b.HasIndex("ConsumableId")
                        .HasDatabaseName("ix_booking_request_items_consumable_id");

                    b.HasIndex("BookingRequestId", "ConsumableId")
                        .IsUnique()
                        .HasDatabaseName("uq_bri");

                    b.ToTable("booking_request_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_request_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Consumable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity")
                        .HasComputedColumnSql("stock_quantity - reserved_quantity", true);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MinStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_consumables");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_cons_low")
                        .HasFilter("stock_quantity <= min_stock_level");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_consumables_name");

                    b.ToTable("consumables", null, t =>
                        {
                            t.HasCheckConstraint("chk_never_oversold", "reserved_quantity <= stock_quantity");

                            t.HasCheckConstraint("ck_consumables_min_stock_level", "min_stock_level >= 0");

                            t.HasCheckConstraint("ck_consumables_reserved_quantity", "reserved_quantity >= 0");

                            t.HasCheckConstraint("ck_consumables_stock_quantity", "stock_quantity >= 0");

                            t.HasCheckConstraint("ck_consumables_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.ConsumableSupplier", b =>
                {
                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumable_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPreferred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preferred");

                    b.Property<decimal>("SupplyPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("supply_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConsumableId", "SupplierId")
                        .HasName("pk_consumable_suppliers");

                    b.HasIndex("ConsumableId")
                        .IsUnique()
                        .HasDatabaseName("ux_preferred")
                        .HasFilter("is_preferred");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_consumable_suppliers_supplier_id");

                    b.ToTable("consumable_suppliers", null, t =>
                        {
                            t.HasCheckConstraint("ck_consumable_suppliers_supply_price", "supply_price >= 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.EmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Queued")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("to_email");

                    b.HasKey("Id")
                        .HasName("pk_email_notifications");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_email_notifications_booking_request_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_email_due");

                    b.ToTable("email_notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_notifications_status", "status IN ('Queued','Sent','Failed','DeadLettered')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.EquipmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_equipment_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_types_name");

                    b.ToTable("equipment_types", (string)null);
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_windows");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_maintenance_windows_room_id");

                    b.ToTable("maintenance_windows", null, t =>
                        {
                            t.HasCheckConstraint("chk_mw_order", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<decimal>("BudgetSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("budget_snapshot");

                    b.Property<decimal>("ConsumableCost")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("consumable_cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("LKR")
                        .HasColumnName("currency");

                    b.Property<decimal>("RoomFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("room_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount")
                        .HasComputedColumnSql("room_fee + consumable_cost", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<bool>("WithinBudget")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("within_budget")
                        .HasComputedColumnSql("room_fee + consumable_cost <= budget_snapshot", true);

                    b.HasKey("Id")
                        .HasName("pk_quotations");

                    b.HasIndex("BookingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_active")
                        .HasFilter("status IN ('Proposed','Approved')");

                    b.HasIndex("BookingRequestId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_quote_version");

                    b.ToTable("quotations", null, t =>
                        {
                            t.HasCheckConstraint("ck_quotations_consumable_cost", "consumable_cost >= 0");

                            t.HasCheckConstraint("ck_quotations_room_fee", "room_fee >= 0");

                            t.HasCheckConstraint("ck_quotations_status", "status IN ('Draft','Proposed','Approved','Rejected','Superseded')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.QuotationLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsumableId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumable_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total")
                        .HasComputedColumnSql("quantity * unit_price", true);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<Guid?>("RoomBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_booking_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_quotation_line_items");

                    b.HasIndex("ConsumableId")
                        .HasDatabaseName("ix_quotation_line_items_consumable_id");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_qli_quote");

                    b.HasIndex("RoomBookingId")
                        .HasDatabaseName("ix_quotation_line_items_room_booking_id");

                    b.ToTable("quotation_line_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_line_shape", "(item_type = 'Room' AND room_booking_id IS NOT NULL AND consumable_id IS NULL) OR (item_type = 'Consumable' AND consumable_id IS NOT NULL AND room_booking_id IS NULL)");

                            t.HasCheckConstraint("ck_quotation_line_items_item_type", "item_type IN ('Room','Consumable')");

                            t.HasCheckConstraint("ck_quotation_line_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_quotation_line_items_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_user");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RoomBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Confirmed")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_room_bookings");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_rb_request");

                    b.HasIndex("RoomId", "StartsAt")
                        .HasDatabaseName("ix_rb_room");

                    b.ToTable("room_bookings", null, t =>
                        {
                            t.HasCheckConstraint("chk_rb_order", "ends_at > starts_at");

                            t.HasCheckConstraint("ck_room_bookings_status", "status IN ('Confirmed','Cancelled','Completed','NoShow')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RoomEquipment", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("EquipmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_type_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("RoomId", "EquipmentTypeId")
                        .HasName("pk_room_equipment");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("ix_room_equipment_equipment_type_id");

                    b.ToTable("room_equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_equipment_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingRequestItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_item_id");

                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumable_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<DateTimeOffset?>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_reservations");

                    b.HasIndex("BookingRequestItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_reservations_booking_request_item_id");

                    b.HasIndex("ConsumableId", "Status")
                        .HasDatabaseName("ix_res_cons");

                    b.ToTable("stock_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservations_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_stock_reservations_status", "status IN ('Pending','Reserved','Released','Used')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<Guid?>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumable_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("StockReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_reservation_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_stock_transactions");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_stock_transactions_booking_request_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_stock_transactions_created_by");

                    b.HasIndex("StockReservationId")
                        .HasDatabaseName("ix_stock_transactions_stock_reservation_id");

                    b.HasIndex("ConsumableId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tx_cons");

                    b.ToTable("stock_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_transactions_quantity", "quantity <> 0");

                            t.HasCheckConstraint("ck_stock_transactions_type", "transaction_type IN ('StockIn','StockOut','Reserve','Release','Adjust')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("department");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxBookingsPerWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_bookings_per_week");

                    b.Property<int>("PenaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("penalty_points");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_number");

                    b.Property<DateOnly?>("SuspendedUntil")
                        .HasColumnType("date")
                        .HasColumnName("suspended_until");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_student_number");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.ToTable("student_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_profiles_max_bookings", "max_bookings_per_week > 0");

                            t.HasCheckConstraint("ck_student_profiles_penalty_points", "penalty_points >= 0");

                            t.HasCheckConstraint("ck_student_profiles_year", "year_of_study BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StudyRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("building");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("qr_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_study_rooms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_study_rooms_name");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("ix_study_rooms_qr_code");

                    b.HasIndex("IsActive", "Capacity")
                        .HasDatabaseName("ix_rooms_search");

                    b.ToTable("study_rooms", null, t =>
                        {
                            t.HasCheckConstraint("ck_study_rooms_capacity", "capacity > 0");

                            t.HasCheckConstraint("ck_study_rooms_hourly_rate", "hourly_rate >= 0");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Student','Librarian','StoreOfficer','Admin')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_request_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Started")
                        .HasColumnName("status");

                    b.Property<int?>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_workflow_executions");

                    b.HasIndex("BookingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_wf_active")
                        .HasFilter("status IN ('Started','InProgress','PendingApproval')");

                    b.ToTable("workflow_executions", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_executions_status", "status IN ('Started','InProgress','PendingApproval','Approved','Rejected','Failed','Completed')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.WorkflowStepLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("agent_name");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<string>("ToolName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ValidationDetails")
                        .HasColumnType("text")
                        .HasColumnName("validation_details");

                    b.Property<string>("ValidationResult")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("validation_result");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step_logs");

                    b.HasIndex("WorkflowExecutionId", "StepNumber")
                        .HasDatabaseName("ix_step_wf");

                    b.HasIndex("WorkflowExecutionId", "StepNumber", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("uq_step");

                    b.ToTable("workflow_step_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_step_logs_validation_result", "validation_result IN ('Pass','Fail','Warning')");
                        });
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_users_decided_by");

                    b.HasOne("StudyHive.Api.Data.Entities.Quotation", "Quotation")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_quotations_quotation_id");

                    b.Navigation("DecidedByUser");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequest", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.StudentProfile", "Student")
                        .WithMany("BookingRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_requests_student_profiles_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequestEquipment", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany("RequiredEquipment")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_request_equipment_booking_requests_booking_request_");

                    b.HasOne("StudyHive.Api.Data.Entities.EquipmentType", "EquipmentType")
                        .WithMany("RequestedBy")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_request_equipment_equipment_types_equipment_type_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequestItem", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany("Items")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_request_items_booking_requests_booking_request_id");

                    b.HasOne("StudyHive.Api.Data.Entities.Consumable", "Consumable")
                        .WithMany("RequestedIn")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_request_items_consumables_consumable_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.ConsumableSupplier", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.Consumable", "Consumable")
                        .WithMany("Suppliers")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumable_suppliers_consumables_consumable_id");

                    b.HasOne("StudyHive.Api.Data.Entities.Supplier", "Supplier")
                        .WithMany("Consumables")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumable_suppliers_suppliers_supplier_id");

                    b.Navigation("Consumable");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.EmailNotification", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_notifications_booking_requests_booking_request_id");

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.MaintenanceWindow", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.StudyRoom", "Room")
                        .WithMany("MaintenanceWindows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_windows_study_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Quotation", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotations_booking_requests_booking_request_id");

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.QuotationLineItem", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quotation_line_items_consumables_consumable_id");

                    b.HasOne("StudyHive.Api.Data.Entities.Quotation", "Quotation")
                        .WithMany("LineItems")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_line_items_quotations_quotation_id");

                    b.HasOne("StudyHive.Api.Data.Entities.RoomBooking", "RoomBooking")
                        .WithMany("QuotationLineItems")
                        .HasForeignKey("RoomBookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quotation_line_items_room_bookings_room_booking_id");

                    b.Navigation("Consumable");

                    b.Navigation("Quotation");

                    b.Navigation("RoomBooking");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RoomBooking", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_bookings_booking_requests_booking_request_id");

                    b.HasOne("StudyHive.Api.Data.Entities.StudyRoom", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_bookings_study_rooms_room_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RoomEquipment", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.EquipmentType", "EquipmentType")
                        .WithMany("Rooms")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_equipment_equipment_types_equipment_type_id");

                    b.HasOne("StudyHive.Api.Data.Entities.StudyRoom", "Room")
                        .WithMany("Equipment")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_equipment_study_rooms_room_id");

                    b.Navigation("EquipmentType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StockReservation", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequestItem", "BookingRequestItem")
                        .WithOne("StockReservation")
                        .HasForeignKey("StudyHive.Api.Data.Entities.StockReservation", "BookingRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservations_booking_request_items_booking_request_it");

                    b.HasOne("StudyHive.Api.Data.Entities.Consumable", "Consumable")
                        .WithMany("Reservations")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservations_consumables_consumable_id");

                    b.Navigation("BookingRequestItem");

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StockTransaction", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_transactions_booking_requests_booking_request_id");

                    b.HasOne("StudyHive.Api.Data.Entities.Consumable", "Consumable")
                        .WithMany("Transactions")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_consumables_consumable_id");

                    b.HasOne("StudyHive.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_users_created_by");

                    b.HasOne("StudyHive.Api.Data.Entities.StockReservation", "StockReservation")
                        .WithMany("Transactions")
                        .HasForeignKey("StockReservationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_transactions_stock_reservations_stock_reservation_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Consumable");

                    b.Navigation("CreatedByUser");

                    b.Navigation("StockReservation");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StudentProfile", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("StudyHive.Api.Data.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.WorkflowExecution", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_executions_booking_requests_booking_request_id");

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.WorkflowStepLog", b =>
                {
                    b.HasOne("StudyHive.Api.Data.Entities.WorkflowExecution", "WorkflowExecution")
                        .WithMany("StepLogs")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_logs_workflow_executions_workflow_execution_id");

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequest", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RequiredEquipment");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.BookingRequestItem", b =>
                {
                    b.Navigation("StockReservation");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Consumable", b =>
                {
                    b.Navigation("RequestedIn");

                    b.Navigation("Reservations");

                    b.Navigation("Suppliers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.EquipmentType", b =>
                {
                    b.Navigation("RequestedBy");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Quotation", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.RoomBooking", b =>
                {
                    b.Navigation("QuotationLineItems");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StockReservation", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StudentProfile", b =>
                {
                    b.Navigation("BookingRequests");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.StudyRoom", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Equipment");

                    b.Navigation("MaintenanceWindows");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Consumables");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("StudyHive.Api.Data.Entities.WorkflowExecution", b =>
                {
                    b.Navigation("StepLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
